feat: add sortChildrenWith
graasp/graasp-sdk pull request #378
Opened 2024-01-19 16:21 UTC by pyphilia

close #377

2024-01-19 16:46 UTC, spaenleh requested changes
Looks good, but I think it should be DiscriminatedItem everywhere.

2024-01-19 16:46 UTC, spaenleh commented on src/utils/item.test.ts
> +import { Item } from '..';
Use `DiscriminatedItem` instead ?

2024-01-19 16:46 UTC, spaenleh commented on src/utils/item.ts
> +import { DiscriminatedItem, Item } from '@/index';
Actually We should not use `Item` in this file.

2024-01-19 16:46 UTC, spaenleh commented on src/utils/item.ts
> +  return children.toSorted(compareFn);
nice !

2024-01-19 16:46 UTC, spaenleh commented on tsconfig.json
> +    "lib": ["esnext"],
What is this used for ? :curious:

2024-01-22 08:51 UTC, pyphilia commented on tsconfig.json
> +    "lib": ["esnext"],
it's necessary to use `toSorted`!

2024-01-22 09:00 UTC, merged