feat: make own validation for password
graasp/graasp-sdk pull request #688
Opened 2024-11-04 08:20 UTC by spaenleh

2024-11-04 08:49 UTC, pyphilia approved these changes

2024-11-04 08:49 UTC, pyphilia commented on src/validation/isPasswordStrong.ts
> +import { countChars, merge } from './utils.js';
Should we add a comment to say it's from a package?

2024-11-04 09:20 UTC, ReidyT requested changes
It's a very good idea to extract the necessary code in terms of saving space compared to the small complexity added to our project 👍

Sounds good to me, I'd just add a few more test cases to completely validate the isStrongPassword code.

2024-11-04 09:20 UTC, ReidyT commented on src/validation/isPasswordStrong.test.ts
It's really good to have tests 🤩
I'd just add a bit more test cases to validate the library code. 

Here is the tests implemented in the library:

```ts
it('should validate strong passwords', () => {
    test({
      validator: 'isStrongPassword',
      args: [{
        minLength: 8,
        minLowercase: 1,
        minUppercase: 1,
        minNumbers: 1,
        minSymbols: 1,
      }],
      valid: [
        '%2%k{7BsL"M%Kd6e',
        'EXAMPLE of very long_password123!',
        'mxH_+2vs&54_+H3P',
        '+&DxJ=X7-4L8jRCD',
        'etV*p%Nr6w&H%FeF',
        '£3.ndSau_7',
        'VaLIDWith\\Symb0l',
      ],
      invalid: [
        '',
        'password',
        'hunter2',
        'hello world',
        'passw0rd',
        'password!',
        'PASSWORD!',
      ],
    });
  });
```

2024-11-04 10:08 UTC, spaenleh commented
@ReidyT Thank you for the suggestion. I have implemented the additional tests and fixed the code smell issues detected by SonarCloud.

2024-11-05 09:06 UTC, ReidyT approved these changes
Really nice! Thanks for this change 🦄

2024-11-05 12:32 UTC, merged